spring.application.name=Exercises

# --- Configurazione H2 ---

# Abilita la console web di H2
spring.h2.console.enabled=true
# Imposta il path per accedere alla console (default è /h2-console)
spring.h2.console.path=/h2-console

# --- Configurazione del DataSource ---

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=

# --- Configurazione JPA/Hibernate ---
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
